Make FLASHBOOT an enum value
Because FLASHBOOT is an enum value, running create_endpoint
throws
   runpod.error.QueryError: Enum "FlashBootType" cannot represent non-enum value: "FLASHBOOT"
if FLASHBOOT is passed as string.