Make FLASHBOOT an enum value (#488)
Because FLASHBOOT is an enum value, running create_endpoint
throws
   runpod.error.QueryError: Enum "FlashBootType" cannot represent non-enum value: "FLASHBOOT"
if FLASHBOOT is passed as string.

Co-authored-by: Dean Quiñanola <deanq@users.noreply.github.com>